site_name: ELTE DATABASES I. AND II. CLASSES PRACTICE NOTES
theme:
  logo: assets/database.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: teal

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Practice Guides:
  - DB1 Practice Guide: topics.md
  - DB2 Practice Guide
- SQL Basics:
  - Relational Model: sql/01_Relational_Model.md
  - SELECT Statement: sql/02_SELECT_Statement.md
  - Set Operators: sql/03_Set_Operators.md
  - Character Functions: sql/04_Character_Functions.md
  - Number Functions: sql/05_Number_Functions.md
  - Date Functions: sql/06_Date_Functions.md
  - Conversion Functions: sql/07_Conversion_Functions.md
  - Aggregate Functions: sql/08_Aggregate_Functions.md
  - Subqueries: sql/09_Subqueries.md
  - Relational Algebra: sql/10_Relational_Algebra.md
  - Joins: sql/11_Joins.md
  - DML: sql/12_DML.md
  - Transactions: sql/13_Transactions.md
  - DDL: sql/14_DDL.md
  - Views: sql/15_Views.md
- PL/SQL Concepts:
  - PL/SQL Basics: pl_sql/01_PL_SQL_Basics.md
  - Cursors: pl_sql/02_Cursors.md
  - Exception Handling: pl_sql/03_Exception_Handling.md
  - Recursion: pl_sql/04_Recursion.md
- PL/SQL Optimization
- Advanced PL/SQL

extra:
  generator: false

copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> Holicza Barnab√°s & ELTE