site_name: ELTE DATABASES I. AND II. CLASSES PRACTICE NOTES
theme:
  logo: assets/database.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: teal

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
- Practice Guides:
  - DB1 Practice Guide: topics.md
  - DB2 Practice Guide: none.md
- SQL Basics:
  - Introduction: sql/01_Introduction.md
  - Basic SQL Statements: sql/02_Basic_sql_statements.md
  - Set Operators: sql/03_Set_Operators.md
  - Data Types: sql/04_Data_types.md
  - SQL Functions: sql/05_Sql_functions.md
  - Character Functions: sql/06_Character_functions.md
  - Number Functions: sql/07_Number_functions.md
  - Date Functions: sql/08_Date_functions.md
  - Conversion Functions: sql/09_Conversion_functions.md
  - Other Functions: sql/10_Other_functions.md
  - Conditional Expressions: sql/11_Conditional_expressions.md
  - Group Functions: sql/12_Group_functions.md
  - Group By: sql/13_Group_by.md
  - Joins: sql/14_Joins.md
  - Subqueries: sql/15_Subqueries.md
  - With: sql/16_With.md
  - DML and DDL: sql/17_DML_DDL.md
  - Views: sql/18_Views.md
  - Relational Algebra: sql/19_Relational_algebra.md
- PL/SQL Concepts:
  - PL/SQL Basics: pl_sql/01_PL_SQL_basics.md
  - Cursors and Collections: pl_sql/02_Cursors and collections.md
  - Exceptions: pl_sql/03_Exceptions.md
  - Recursion: pl_sql/04_Recurson.md
- PL/SQL Optimization: pl_sql_optimization/none.md
- Advanced PL/SQL: advanced_pl_sql/none.md

extra:
  generator: false

copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> Holicza Barnab√°s & ELTE